### PR TITLE
My iteration on the archive script

### PR DESCRIPTION
**Pull request by martinthomson**
@MikeBishop WDYT?  Do you want to see a PR on your branch?

### CODE REVIEW

**Comment by martinthomson** [comment]
The email address came through empty in my testing.  Were you able to get an email address somehow?

I wasn't confident in removing the `userFields` fragment though.  I assume that you would just have `author { login }` where you wanted that information.

**Comment by MikeBishop** [comment]
You can select a public email address in your Github profile; it's empty for anyone who hasn't. It's not universally empty, or universally filled.

I'd love to have an "if not empty," but GraphQL doesn't have the concept of filtering on values to decide whether to return something.

**Comment by martinthomson** [comment]
I see.  In that case, I think I'll limit this to the login name.  I realize that the email thing might help in the sense that it has meaning in IETF-land, but I don't think we need to avoid using the user profile for information related to users.  For instance, I had to go looking for another way to display an avatar to get the HTML viewer working.  This could save information about every user to the archive, such as email address and avatars, but that can wait.  Right now, I think the priority is getting the information displayed correctly.

**Comment by MikeBishop** [comment]
Perhaps a similar treatment to labels - capture just the login in issues, then gather the list of emails, avatars, etc. in a separate top-level list.

**Pull request merged**
