### PR TITLE
Smaller ToC

### PR DESCRIPTION
**Pull request by mnot**
for #140

### CODE REVIEW

**Comment by martinthomson** [comment]
This doesn't work with the HTML produced by xml2rfc sadly.

**Comment by mnot** [comment]
Can you give me a sample or point me to one? That way I can test against both. (I've created a local samples/ directory; something to consider?)

**Comment by martinthomson** [comment]
See QUIC.

**Comment by martinthomson** [comment]
Yep, looks good.  I've tweaked further, and simplified a lot.  Let me know what you think of the new look.

**Pull request closed without merging**
