### PR TITLE
Use shell to check contents of .targets.mk

### LINKED ISSUE #136: .targets.mk always builds
Appears to be because `$(TARGETS_DRAFTS)` and `$(TARGETS_TAGS)` are used to check whether the file needs to be rebuilt prior to the include, so the answer is always yes.  Including first, then re-including after building .targets.mk causes warning.

Maybe need to hand this off to shell to decide if there's something missing?

### PR DESCRIPTION
**Pull request by MikeBishop**
Fixes #136, albeit a little ugly.

### CODE REVIEW

**Comment by MikeBishop** [comment]
(Drops the time to run `make -q` on the http-extensions repo from 39 seconds to 4.9 seconds.)

**Comment by martinthomson** [comment]
Thanks for taking the time to look into this.  You are right, I never managed to avoid that overhead.

On Linux, it's much faster, so I didn't notice.

I think that this is too complex though.  Take a look at my PR for this and see what you think.

**Comment by MikeBishop** [comment]
As usual, we're trading off complexity versus corner cases.  Mine doesn't assume they're guaranteed to be in the same order (because I wasn't certain how deterministic that is), plus doesn't rebuild on the removal of a draft or tag, because you don't actually need to.  If order is deterministic, that might be a reasonable price to pay to have a simpler (and constant-time) check.

Otherwise, I wonder if there's a good way to meet in the middle -- could you use your approach of reading the lines into make, but then use `$(words $(filter-out $(drafts-in-file) $(tags-in-file),$(drafts) $(tags)))` and check that it's zero?

**Comment by martinthomson** [comment]
Order is consistent enough.  I don't think that there are guarantees, but I could slap in a "sort" call for these variables to make it more certain.

`$(words $(filter-out ...))` is more work.  If we canonicalize, then it's probably faster. Given that `$(wildcard)` seems to produce sorted output, that seems easier to sort than it would be to do an O(N^2) operation.

**Comment by martinthomson** [comment]
Oh, I already have drafts sorted.  Using `git tag --sort` might address the other concern (it seems to sort on name by default, but that's not a documented feature).

**Comment by MikeBishop** [comment]
Works for me.  The trade-off of a spurious rebuild on draft deletion is probably cheap enough to pay.  I might also look and see if I can make the rebuild itself faster on WSL, but that's probably just a factor of so many drafts and tags in this particular repo.

**Comment by martinthomson** [comment]
Yeah, QUIC is a pig (http-extensions is also a pig).

**Pull request merged**
