### PR TITLE
Don't build diffs if no previous version

### PR DESCRIPTION
**Pull request by MikeBishop**
Let's try this again.  I think this works now.

### CODE REVIEW

**Comment by martinthomson** [comment]
Wow, it works, but it makes the code even harder to understand.

**Comment by MikeBishop** [comment]
Do you really think that's possible at this point?  I spent about 45 minutes just *understanding* it enough to make a 2-3 line change!

**Comment by martinthomson** [comment]
As I said, it's the black arts in there.  I think that I prefer the new PR I put up for simplicity.  At least it's only shell scripting that way.

**Comment by martinthomson** [comment]
BTW, 45 min well spent.

**Pull request merged**
